const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('liveAgent', {
  protectWindow: enabled => ipcRenderer.invoke('protect-window', enabled),
  setLiveMode: enabled => ipcRenderer.invoke('set-live-mode', enabled),
  envOpenAiAvailable: () => ipcRenderer.invoke('env-openai-available'),
  localTranscriberStatus: () => ipcRenderer.invoke('local-transcriber-status'),
  localTranscribe: payload => ipcRenderer.invoke('local-transcribe', payload),
  displaySources: () => ipcRenderer.invoke('display-sources'),
  setDisplaySource: sourceId => ipcRenderer.invoke('set-display-source', sourceId),
  apiRequest: request => ipcRenderer.invoke('api-request', request),
  quitApp: () => ipcRenderer.invoke('quit-app'),
  chooseImage: () => ipcRenderer.invoke('choose-image'),
  readImageData: filePath => ipcRenderer.invoke('read-image-data', filePath),
  captureScreenImage: () => ipcRenderer.invoke('capture-screen-image'),
  chooseFiles: () => ipcRenderer.invoke('choose-files'),
  readTextFile: filePath => ipcRenderer.invoke('read-text-file', filePath),
  openOverlay: () => ipcRenderer.invoke('open-overlay'),
  closeOverlay: () => ipcRenderer.invoke('close-overlay'),
  setOverlayPosition: position => ipcRenderer.invoke('set-overlay-position', position),
  updateOverlay: payload => ipcRenderer.invoke('update-overlay', payload),
  sendOverlayCommand: command => ipcRenderer.invoke('overlay-command', command),
  openExternal: url => ipcRenderer.invoke('open-external', url),
  webSearch: query => ipcRenderer.invoke('web-search', query),
  agentSkills: payload => ipcRenderer.invoke('agent-skills', payload),
  openAgentSkillsFolder: () => ipcRenderer.invoke('open-agent-skills-folder'),
  vaultState: () => ipcRenderer.invoke('vault-state'),
  vaultImport: () => ipcRenderer.invoke('vault-import'),
  vaultContext: query => ipcRenderer.invoke('vault-context', query),
  vaultDeleteFile: id => ipcRenderer.invoke('vault-delete-file', id),
  vaultClear: () => ipcRenderer.invoke('vault-clear'),
  vaultExport: () => ipcRenderer.invoke('vault-export'),
  vaultRestore: () => ipcRenderer.invoke('vault-restore'),
  workspaceState: () => ipcRenderer.invoke('workspace-state'),
  workspaceAddRoot: () => ipcRenderer.invoke('workspace-add-root'),
  workspaceRemoveRoot: root => ipcRenderer.invoke('workspace-remove-root', root),
  workspaceRefresh: () => ipcRenderer.invoke('workspace-refresh'),
  workspaceContext: query => ipcRenderer.invoke('workspace-context', query),
  workspaceReadFile: filePath => ipcRenderer.invoke('workspace-read-file', filePath),
  vaultSaveMemory: memory => ipcRenderer.invoke('vault-save-memory', memory),
  vaultDeleteMemory: id => ipcRenderer.invoke('vault-delete-memory', id),
  vaultSaveConversation: conversation => ipcRenderer.invoke('vault-save-conversation', conversation),
  vaultDeleteConversation: id => ipcRenderer.invoke('vault-delete-conversation', id),
  onOverlayData: callback => ipcRenderer.on('overlay-data', (_event, payload) => callback(payload)),
  onOverlayCommand: callback => ipcRenderer.on('overlay-command', (_event, payload) => callback(payload)),
  secureStore: value => ipcRenderer.invoke('secure-store', value),
  secureUnstore: value => ipcRenderer.invoke('secure-unstore', value)
});
